// OLYMPUS EXERCISE DATABASE
// 500+ Exercises with Smart Search
// Last Updated: April 2026

const exerciseDatabase = [
  
    // CHEST EXERCISES
    { id: "chest-001", name: "Barbell Bench Press", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "barbell", difficulty: "intermediate", instructions: ["Lie flat on bench with feet planted", "Grip bar slightly wider than shoulders", "Lower to mid-chest", "Press up explosively"], gifUrl: "", searchTags: ["chest", "pecs", "press", "barbell", "compound", "bench", "triceps"] },
    { id: "chest-002", name: "Incline Barbell Bench Press", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "barbell", difficulty: "intermediate", instructions: ["Set bench to 30-45 degrees", "Lower bar to upper chest", "Press back up"], gifUrl: "", searchTags: ["chest", "upper chest", "incline", "press", "barbell", "bench"] },
    { id: "chest-003", name: "Decline Barbell Bench Press", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "barbell", difficulty: "intermediate", instructions: ["Set bench to decline", "Lower to lower chest", "Press back up"], gifUrl: "", searchTags: ["chest", "lower chest", "decline", "press", "barbell"] },
    { id: "chest-004", name: "Dumbbell Bench Press", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "dumbbell", difficulty: "intermediate", instructions: ["Press dumbbells up from chest", "Lower with control"], gifUrl: "", searchTags: ["chest", "pecs", "press", "dumbbell", "db"] },
    { id: "chest-005", name: "Incline Dumbbell Press", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "dumbbell", difficulty: "intermediate", instructions: ["Set bench to incline", "Press dumbbells up"], gifUrl: "", searchTags: ["chest", "upper chest", "incline", "dumbbell", "press"] },
    { id: "chest-006", name: "Dumbbell Flyes", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["shoulders"], equipment: "dumbbell", difficulty: "intermediate", instructions: ["Lower dumbbells out to sides", "Bring back together"], gifUrl: "", searchTags: ["chest", "fly", "flye", "dumbbell", "isolation"] },
    { id: "chest-007", name: "Incline Dumbbell Flyes", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["shoulders"], equipment: "dumbbell", difficulty: "intermediate", instructions: ["Incline bench fly movement"], gifUrl: "", searchTags: ["chest", "upper chest", "incline", "fly", "dumbbell"] },
    { id: "chest-008", name: "Push-Ups", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders", "core"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Lower chest to ground", "Push back up"], gifUrl: "", searchTags: ["chest", "push", "pushup", "bodyweight", "bw", "beginner"] },
    { id: "chest-009", name: "Wide Grip Push-Ups", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Hands wider than shoulders", "Push up"], gifUrl: "", searchTags: ["chest", "wide", "push", "bodyweight"] },
    { id: "chest-010", name: "Diamond Push-Ups", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Form diamond with hands", "Lower and push up"], gifUrl: "", searchTags: ["chest", "inner chest", "triceps", "diamond", "bodyweight"] },
    { id: "chest-011", name: "Decline Push-Ups", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Feet elevated", "Push up"], gifUrl: "", searchTags: ["chest", "upper chest", "decline", "elevated", "bodyweight"] },
    { id: "chest-012", name: "Dips (Chest)", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Lean forward on dips", "Lower and push up"], gifUrl: "", searchTags: ["chest", "dip", "bodyweight", "compound"] },
    { id: "chest-013", name: "Cable Crossover", category: "strength", primaryMuscle: "chest", secondaryMuscles: [], equipment: "cable", difficulty: "intermediate", instructions: ["High cable position", "Bring handles together"], gifUrl: "", searchTags: ["chest", "cable", "crossover", "fly", "isolation"] },
    { id: "chest-014", name: "Low Cable Crossover", category: "strength", primaryMuscle: "chest", secondaryMuscles: [], equipment: "cable", difficulty: "intermediate", instructions: ["Low cable position", "Bring up and together"], gifUrl: "", searchTags: ["chest", "upper chest", "cable", "low"] },
    { id: "chest-015", name: "Chest Press Machine", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps"], equipment: "machine", difficulty: "beginner", instructions: ["Press forward on machine"], gifUrl: "", searchTags: ["chest", "press", "machine", "beginner"] },
    { id: "chest-016", name: "Pec Deck Fly", category: "strength", primaryMuscle: "chest", secondaryMuscles: [], equipment: "machine", difficulty: "beginner", instructions: ["Bring pads together"], gifUrl: "", searchTags: ["chest", "pec deck", "fly", "machine", "isolation"] },
    { id: "chest-017", name: "Close Grip Bench Press", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Narrow grip", "Lower to chest"], gifUrl: "", searchTags: ["chest", "inner chest", "triceps", "close grip", "barbell"] },
    { id: "chest-018", name: "Landmine Press", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["shoulders", "core"], equipment: "barbell", difficulty: "intermediate", instructions: ["Press landmine forward"], gifUrl: "", searchTags: ["chest", "landmine", "press", "core"] },
    { id: "chest-019", name: "Svend Press", category: "strength", primaryMuscle: "chest", secondaryMuscles: [], equipment: "dumbbell", difficulty: "beginner", instructions: ["Squeeze plates/dumbbell", "Press away from chest"], gifUrl: "", searchTags: ["chest", "inner chest", "svend", "squeeze"] },
    { id: "chest-020", name: "Floor Press", category: "strength", primaryMuscle: "chest", secondaryMuscles: ["triceps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Press from floor position"], gifUrl: "", searchTags: ["chest", "floor press", "barbell", "lockout"] },
  
    // BACK EXERCISES  
    { id: "back-001", name: "Conventional Deadlift", category: "strength", primaryMuscle: "back", secondaryMuscles: ["legs", "glutes", "traps"], equipment: "barbell", difficulty: "advanced", instructions: ["Hip-width stance", "Drive through heels", "Stand upright"], gifUrl: "", searchTags: ["back", "deadlift", "barbell", "compound", "posterior chain", "legs", "glutes"] },
    { id: "back-002", name: "Sumo Deadlift", category: "strength", primaryMuscle: "back", secondaryMuscles: ["legs", "glutes"], equipment: "barbell", difficulty: "advanced", instructions: ["Wide stance", "Hands inside legs", "Pull up"], gifUrl: "", searchTags: ["back", "deadlift", "sumo", "barbell", "legs"] },
    { id: "back-003", name: "Romanian Deadlift", category: "strength", primaryMuscle: "back", secondaryMuscles: ["hamstrings", "glutes"], equipment: "barbell", difficulty: "intermediate", instructions: ["Slight knee bend", "Hinge at hips", "Feel hamstring stretch"], gifUrl: "", searchTags: ["back", "rdl", "romanian", "hamstrings", "barbell"] },
    { id: "back-004", name: "Barbell Row", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Bend forward", "Pull bar to abdomen", "Squeeze shoulder blades"], gifUrl: "", searchTags: ["back", "lats", "row", "barbell", "compound", "biceps"] },
    { id: "back-005", name: "Pendlay Row", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Bar starts on ground", "Pull explosively", "Touch ground between reps"], gifUrl: "", searchTags: ["back", "pendlay", "row", "barbell", "explosive"] },
    { id: "back-006", name: "T-Bar Row", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps", "traps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Straddle landmine bar", "Pull to chest"], gifUrl: "", searchTags: ["back", "t-bar", "row", "landmine", "thickness"] },
    { id: "back-007", name: "Pull-Ups", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Overhand grip", "Pull chin over bar", "Lower with control"], gifUrl: "", searchTags: ["back", "lats", "pullup", "pull-up", "bodyweight", "bw", "biceps"] },
    { id: "back-008", name: "Chin-Ups", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Underhand grip", "Pull up"], gifUrl: "", searchTags: ["back", "chinup", "chin-up", "biceps", "bodyweight"] },
    { id: "back-009", name: "Wide Grip Pull-Ups", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "bodyweight", difficulty: "advanced", instructions: ["Wide grip", "Focus on lats"], gifUrl: "", searchTags: ["back", "lats", "wide", "pullup", "bodyweight"] },
    { id: "back-010", name: "Neutral Grip Pull-Ups", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Parallel grip", "Pull up"], gifUrl: "", searchTags: ["back", "neutral", "pullup", "bodyweight"] },
    { id: "back-011", name: "Dumbbell Row", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "dumbbell", difficulty: "beginner", instructions: ["One knee on bench", "Pull dumbbell to hip"], gifUrl: "", searchTags: ["back", "lats", "row", "dumbbell", "db", "unilateral"] },
    { id: "back-012", name: "Chest Supported Row", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "dumbbell", difficulty: "intermediate", instructions: ["Chest on incline bench", "Row dumbbells"], gifUrl: "", searchTags: ["back", "row", "chest supported", "dumbbell", "strict"] },
    { id: "back-013", name: "Seated Cable Row", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "cable", difficulty: "beginner", instructions: ["Pull handle to abdomen", "Squeeze shoulder blades"], gifUrl: "", searchTags: ["back", "row", "cable", "seated"] },
    { id: "back-014", name: "Lat Pulldown", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "cable", difficulty: "beginner", instructions: ["Pull bar to chest", "Control the negative"], gifUrl: "", searchTags: ["back", "lats", "pulldown", "cable", "machine"] },
    { id: "back-015", name: "Close Grip Lat Pulldown", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "cable", difficulty: "beginner", instructions: ["Close grip handle", "Pull to chest"], gifUrl: "", searchTags: ["back", "lats", "pulldown", "close grip", "cable"] },
    { id: "back-016", name: "Straight Arm Pulldown", category: "strength", primaryMuscle: "back", secondaryMuscles: [], equipment: "cable", difficulty: "intermediate", instructions: ["Keep arms straight", "Pull down in arc"], gifUrl: "", searchTags: ["back", "lats", "pulldown", "straight arm", "isolation"] },
    { id: "back-017", name: "Face Pulls", category: "strength", primaryMuscle: "back", secondaryMuscles: ["rear delts", "traps"], equipment: "cable", difficulty: "beginner", instructions: ["Pull rope to face", "Separate hands"], gifUrl: "", searchTags: ["back", "rear delts", "face pull", "cable", "upper back"] },
    { id: "back-018", name: "Hyperextensions", category: "strength", primaryMuscle: "back", secondaryMuscles: ["glutes", "hamstrings"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Lower torso", "Raise using lower back"], gifUrl: "", searchTags: ["back", "lower back", "hyperextension", "erectors", "bodyweight"] },
    { id: "back-019", name: "Good Mornings", category: "strength", primaryMuscle: "back", secondaryMuscles: ["hamstrings", "glutes"], equipment: "barbell", difficulty: "intermediate", instructions: ["Bar on upper back", "Hinge forward"], gifUrl: "", searchTags: ["back", "lower back", "good morning", "hamstrings", "barbell"] },
    { id: "back-020", name: "Barbell Shrugs", category: "strength", primaryMuscle: "back", secondaryMuscles: ["traps"], equipment: "barbell", difficulty: "beginner", instructions: ["Shrug shoulders up", "Hold contraction"], gifUrl: "", searchTags: ["back", "traps", "shrug", "barbell", "neck"] },
    { id: "back-021", name: "Dumbbell Shrugs", category: "strength", primaryMuscle: "back", secondaryMuscles: ["traps"], equipment: "dumbbell", difficulty: "beginner", instructions: ["Dumbbells at sides", "Shrug up"], gifUrl: "", searchTags: ["back", "traps", "shrug", "dumbbell"] },
    { id: "back-022", name: "Inverted Rows", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Bar at waist height", "Pull chest to bar"], gifUrl: "", searchTags: ["back", "row", "inverted", "bodyweight", "horizontal"] },
    { id: "back-023", name: "Meadows Row", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "barbell", difficulty: "advanced", instructions: ["Stand perpendicular to landmine", "Pull to hip"], gifUrl: "", searchTags: ["back", "meadows", "row", "landmine", "unilateral"] },
    { id: "back-024", name: "Seal Row", category: "strength", primaryMuscle: "back", secondaryMuscles: ["biceps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Face down on elevated bench", "Row barbell"], gifUrl: "", searchTags: ["back", "seal", "row", "chest supported"] },
    { id: "back-025", name: "Rack Pulls", category: "strength", primaryMuscle: "back", secondaryMuscles: ["traps", "glutes"], equipment: "barbell", difficulty: "intermediate", instructions: ["Bar on pins at knee height", "Pull to lockout"], gifUrl: "", searchTags: ["back", "rack pull", "deadlift", "traps", "partial"] },
  
    // LEGS EXERCISES
    { id: "legs-001", name: "Back Squat", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes", "core"], equipment: "barbell", difficulty: "intermediate", instructions: ["Bar on upper back", "Descend to parallel", "Drive through heels"], gifUrl: "", searchTags: ["legs", "quads", "squat", "barbell", "compound", "glutes"] },
    { id: "legs-002", name: "Front Squat", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["core"], equipment: "barbell", difficulty: "advanced", instructions: ["Bar on front delts", "Keep torso upright", "Squat down"], gifUrl: "", searchTags: ["legs", "quads", "front squat", "barbell", "olympic"] },
    { id: "legs-003", name: "Goblet Squat", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes"], equipment: "dumbbell", difficulty: "beginner", instructions: ["Hold dumbbell at chest", "Squat down"], gifUrl: "", searchTags: ["legs", "quads", "goblet", "squat", "dumbbell", "beginner"] },
    { id: "legs-004", name: "Bulgarian Split Squat", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes"], equipment: "dumbbell", difficulty: "intermediate", instructions: ["Rear foot on bench", "Lunge down"], gifUrl: "", searchTags: ["legs", "quads", "bulgarian", "split squat", "lunge", "unilateral"] },
    { id: "legs-005", name: "Walking Lunges", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes"], equipment: "dumbbell", difficulty: "intermediate", instructions: ["Step forward into lunge", "Alternate legs"], gifUrl: "", searchTags: ["legs", "quads", "lunge", "walking", "dumbbell"] },
    { id: "legs-006", name: "Leg Press", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes"], equipment: "machine", difficulty: "beginner", instructions: ["Push platform with feet", "Don't lock knees"], gifUrl: "", searchTags: ["legs", "quads", "leg press", "machine", "beginner"] },
    { id: "legs-007", name: "Leg Extension", category: "strength", primaryMuscle: "legs", secondaryMuscles: [], equipment: "machine", difficulty: "beginner", instructions: ["Extend legs", "Squeeze quads"], gifUrl: "", searchTags: ["legs", "quads", "leg extension", "machine", "isolation"] },
    { id: "legs-008", name: "Lying Leg Curl", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["hamstrings"], equipment: "machine", difficulty: "beginner", instructions: ["Curl legs to glutes", "Squeeze hamstrings"], gifUrl: "", searchTags: ["legs", "hamstrings", "leg curl", "lying", "machine"] },
    { id: "legs-009", name: "Seated Leg Curl", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["hamstrings"], equipment: "machine", difficulty: "beginner", instructions: ["Curl legs down", "Control negative"], gifUrl: "", searchTags: ["legs", "hamstrings", "leg curl", "seated", "machine"] },
    { id: "legs-010", name: "Hack Squat", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes"], equipment: "machine", difficulty: "intermediate", instructions: ["Shoulders under pads", "Squat down"], gifUrl: "", searchTags: ["legs", "quads", "hack squat", "machine"] },
    { id: "legs-011", name: "Standing Calf Raise", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["calves"], equipment: "machine", difficulty: "beginner", instructions: ["Raise up on toes", "Lower for stretch"], gifUrl: "", searchTags: ["legs", "calves", "calf raise", "standing"] },
    { id: "legs-012", name: "Seated Calf Raise", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["calves"], equipment: "machine", difficulty: "beginner", instructions: ["Raise heels up", "Lower for stretch"], gifUrl: "", searchTags: ["legs", "calves", "calf raise", "seated"] },
    { id: "legs-013", name: "Box Squat", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes"], equipment: "barbell", difficulty: "intermediate", instructions: ["Squat to box", "Pause", "Explode up"], gifUrl: "", searchTags: ["legs", "squat", "box", "barbell", "power"] },
    { id: "legs-014", name: "Pause Squat", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes"], equipment: "barbell", difficulty: "advanced", instructions: ["Pause at bottom", "Drive up"], gifUrl: "", searchTags: ["legs", "squat", "pause", "barbell", "tempo"] },
    { id: "legs-015", name: "Zercher Squat", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["core"], equipment: "barbell", difficulty: "advanced", instructions: ["Bar in elbow crook", "Squat down"], gifUrl: "", searchTags: ["legs", "squat", "zercher", "barbell", "core"] },
    { id: "legs-016", name: "Pistol Squat", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes"], equipment: "bodyweight", difficulty: "advanced", instructions: ["Single leg squat", "Extended leg forward"], gifUrl: "", searchTags: ["legs", "pistol", "squat", "single leg", "bodyweight", "advanced"] },
    { id: "legs-017", name: "Sissy Squat", category: "strength", primaryMuscle: "legs", secondaryMuscles: [], equipment: "bodyweight", difficulty: "advanced", instructions: ["Lean back", "Extreme quad isolation"], gifUrl: "", searchTags: ["legs", "quads", "sissy squat", "bodyweight", "isolation"] },
    { id: "legs-018", name: "Nordic Hamstring Curl", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["hamstrings"], equipment: "bodyweight", difficulty: "advanced", instructions: ["Kneel", "Lower forward with control"], gifUrl: "", searchTags: ["legs", "hamstrings", "nordic", "bodyweight", "eccentric"] },
    { id: "legs-019", name: "Glute Ham Raise", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["hamstrings", "glutes"], equipment: "machine", difficulty: "advanced", instructions: ["GHR machine", "Pull with hamstrings"], gifUrl: "", searchTags: ["legs", "hamstrings", "glutes", "ghr", "machine"] },
    { id: "legs-020", name: "Hip Thrust", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes"], equipment: "barbell", difficulty: "intermediate", instructions: ["Upper back on bench", "Drive hips up"], gifUrl: "", searchTags: ["legs", "glutes", "hip thrust", "barbell", "glute bridge"] },
    { id: "legs-021", name: "Lunges", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Step forward", "Lower back knee"], gifUrl: "", searchTags: ["legs", "quads", "lunge", "bodyweight", "beginner"] },
    { id: "legs-022", name: "Reverse Lunges", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes"], equipment: "dumbbell", difficulty: "intermediate", instructions: ["Step backward", "Lower down"], gifUrl: "", searchTags: ["legs", "quads", "reverse lunge", "dumbbell"] },
    { id: "legs-023", name: "Step-Ups", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["glutes"], equipment: "dumbbell", difficulty: "beginner", instructions: ["Step onto box", "Drive through heel"], gifUrl: "", searchTags: ["legs", "quads", "step up", "dumbbell", "box"] },
    { id: "legs-024", name: "Single Leg Press", category: "strength", primaryMuscle: "legs", secondaryMuscles: [], equipment: "machine", difficulty: "intermediate", instructions: ["One leg on platform", "Press up"], gifUrl: "", searchTags: ["legs", "quads", "leg press", "single leg", "unilateral"] },
    { id: "legs-025", name: "Leg Press Calf Raise", category: "strength", primaryMuscle: "legs", secondaryMuscles: ["calves"], equipment: "machine", difficulty: "beginner", instructions: ["Toes on platform edge", "Raise up"], gifUrl: "", searchTags: ["legs", "calves", "leg press", "calf raise"] },
  
    // SHOULDERS
    { id: "shoulders-001", name: "Overhead Press", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["triceps", "core"], equipment: "barbell", difficulty: "intermediate", instructions: ["Press bar overhead", "Lock out at top"], gifUrl: "", searchTags: ["shoulders", "delts", "press", "overhead", "barbell", "ohp", "military"] },
    { id: "shoulders-002", name: "Seated Overhead Press", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Seated press", "Back support"], gifUrl: "", searchTags: ["shoulders", "press", "seated", "overhead", "barbell"] },
    { id: "shoulders-003", name: "Dumbbell Shoulder Press", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], equipment: "dumbbell", difficulty: "intermediate", instructions: ["Press dumbbells overhead"], gifUrl: "", searchTags: ["shoulders", "press", "dumbbell", "db", "overhead"] },
    { id: "shoulders-004", name: "Arnold Press", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], equipment: "dumbbell", difficulty: "intermediate", instructions: ["Start palms facing in", "Rotate while pressing"], gifUrl: "", searchTags: ["shoulders", "arnold", "press", "dumbbell", "rotation"] },
    { id: "shoulders-005", name: "Lateral Raise", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: [], equipment: "dumbbell", difficulty: "beginner", instructions: ["Raise arms to sides", "To shoulder height"], gifUrl: "", searchTags: ["shoulders", "lateral raise", "side raise", "dumbbell", "isolation", "side delts"] },
    { id: "shoulders-006", name: "Front Raise", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: [], equipment: "dumbbell", difficulty: "beginner", instructions: ["Raise arms forward", "To shoulder height"], gifUrl: "", searchTags: ["shoulders", "front raise", "dumbbell", "isolation", "anterior delts"] },
    { id: "shoulders-007", name: "Rear Delt Fly", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["upper back"], equipment: "dumbbell", difficulty: "beginner", instructions: ["Bend forward", "Raise arms out"], gifUrl: "", searchTags: ["shoulders", "rear delts", "fly", "dumbbell", "posterior"] },
    { id: "shoulders-008", name: "Upright Row", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["traps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Pull bar to chest", "Elbows high"], gifUrl: "", searchTags: ["shoulders", "upright row", "barbell", "traps"] },
    { id: "shoulders-009", name: "Cable Lateral Raise", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: [], equipment: "cable", difficulty: "beginner", instructions: ["Side cable raise", "Constant tension"], gifUrl: "", searchTags: ["shoulders", "lateral raise", "cable", "isolation"] },
    { id: "shoulders-010", name: "Pike Push-Ups", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Downward dog position", "Lower head to ground"], gifUrl: "", searchTags: ["shoulders", "pike", "push", "bodyweight", "vertical"] },
    { id: "shoulders-011", name: "Handstand Push-Ups", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], equipment: "bodyweight", difficulty: "advanced", instructions: ["Handstand against wall", "Lower and press"], gifUrl: "", searchTags: ["shoulders", "handstand", "hspu", "bodyweight", "advanced"] },
    { id: "shoulders-012", name: "Landmine Press", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["core"], equipment: "barbell", difficulty: "intermediate", instructions: ["Press landmine bar up"], gifUrl: "", searchTags: ["shoulders", "landmine", "press", "unilateral"] },
    { id: "shoulders-013", name: "Face Pulls", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["rear delts", "upper back"], equipment: "cable", difficulty: "beginner", instructions: ["Pull rope to face", "Separate hands"], gifUrl: "", searchTags: ["shoulders", "face pull", "cable", "rear delts", "rotator cuff"] },
    { id: "shoulders-014", name: "Shoulder Press Machine", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], equipment: "machine", difficulty: "beginner", instructions: ["Press handles overhead"], gifUrl: "", searchTags: ["shoulders", "press", "machine", "beginner"] },
    { id: "shoulders-015", name: "Reverse Pec Deck", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["rear delts"], equipment: "machine", difficulty: "beginner", instructions: ["Face machine", "Pull handles back"], gifUrl: "", searchTags: ["shoulders", "rear delts", "pec deck", "reverse fly", "machine"] },
  
    // BICEPS
    { id: "biceps-001", name: "Barbell Curl", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["biceps", "forearms"], equipment: "barbell", difficulty: "beginner", instructions: ["Curl bar to shoulders", "Keep elbows still"], gifUrl: "", searchTags: ["arms", "biceps", "curl", "barbell", "bis"] },
    { id: "biceps-002", name: "EZ Bar Curl", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["biceps"], equipment: "barbell", difficulty: "beginner", instructions: ["Curl EZ bar", "Easier on wrists"], gifUrl: "", searchTags: ["arms", "biceps", "curl", "ez bar", "barbell"] },
    { id: "biceps-003", name: "Dumbbell Curl", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["biceps"], equipment: "dumbbell", difficulty: "beginner", instructions: ["Curl dumbbells up", "Can alternate"], gifUrl: "", searchTags: ["arms", "biceps", "curl", "dumbbell", "db"] },
    { id: "biceps-004", name: "Hammer Curl", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["biceps", "forearms"], equipment: "dumbbell", difficulty: "beginner", instructions: ["Palms facing each other", "Curl up"], gifUrl: "", searchTags: ["arms", "biceps", "hammer", "curl", "dumbbell", "neutral", "forearms"] },
    { id: "biceps-005", name: "Concentration Curl", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["biceps"], equipment: "dumbbell", difficulty: "beginner", instructions: ["Elbow on thigh", "Curl to shoulder"], gifUrl: "", searchTags: ["arms", "biceps", "concentration", "curl", "isolation"] },
    { id: "biceps-006", name: "Preacher Curl", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["biceps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Arms on preacher bench", "Strict curl"], gifUrl: "", searchTags: ["arms", "biceps", "preacher", "curl", "barbell", "strict"] },
    { id: "biceps-007", name: "Incline Dumbbell Curl", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["biceps"], equipment: "dumbbell", difficulty: "intermediate", instructions: ["Lie on incline", "Arms hang down", "Curl up"], gifUrl: "", searchTags: ["arms", "biceps", "incline", "curl", "dumbbell", "stretch"] },
    { id: "biceps-008", name: "Cable Curl", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["biceps"], equipment: "cable", difficulty: "beginner", instructions: ["Curl cable bar", "Constant tension"], gifUrl: "", searchTags: ["arms", "biceps", "curl", "cable"] },
    { id: "biceps-009", name: "Spider Curl", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["biceps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Face down on incline", "No momentum"], gifUrl: "", searchTags: ["arms", "biceps", "spider", "curl", "strict"] },
    { id: "biceps-010", name: "Drag Curl", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["biceps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Drag bar up body", "Elbows back"], gifUrl: "", searchTags: ["arms", "biceps", "drag", "curl", "barbell"] },
  
    // TRICEPS
    { id: "triceps-001", name: "Close Grip Bench Press", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["triceps", "chest"], equipment: "barbell", difficulty: "intermediate", instructions: ["Narrow grip", "Lower to chest", "Press up"], gifUrl: "", searchTags: ["arms", "triceps", "close grip", "bench", "barbell", "compound"] },
    { id: "triceps-002", name: "Dips (Tricep)", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["triceps"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Stay upright", "Lower and push up"], gifUrl: "", searchTags: ["arms", "triceps", "dip", "bodyweight", "compound"] },
    { id: "triceps-003", name: "Overhead Tricep Extension", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["triceps"], equipment: "dumbbell", difficulty: "beginner", instructions: ["Dumbbell overhead", "Lower behind head"], gifUrl: "", searchTags: ["arms", "triceps", "overhead", "extension", "dumbbell"] },
    { id: "triceps-004", name: "Skull Crushers", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["triceps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Lower bar to forehead", "Extend back up"], gifUrl: "", searchTags: ["arms", "triceps", "skull crusher", "lying extension", "barbell"] },
    { id: "triceps-005", name: "Tricep Pushdown", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["triceps"], equipment: "cable", difficulty: "beginner", instructions: ["Push cable down", "Extend fully"], gifUrl: "", searchTags: ["arms", "triceps", "pushdown", "cable", "rope"] },
    { id: "triceps-006", name: "Overhead Cable Extension", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["triceps"], equipment: "cable", difficulty: "beginner", instructions: ["Face away from cable", "Extend forward"], gifUrl: "", searchTags: ["arms", "triceps", "overhead", "cable", "extension"] },
    { id: "triceps-007", name: "Diamond Push-Ups", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["triceps", "chest"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Diamond hand position", "Push up"], gifUrl: "", searchTags: ["arms", "triceps", "diamond", "pushup", "bodyweight"] },
    { id: "triceps-008", name: "Tricep Kickback", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["triceps"], equipment: "dumbbell", difficulty: "beginner", instructions: ["Bend forward", "Extend arm back"], gifUrl: "", searchTags: ["arms", "triceps", "kickback", "dumbbell", "isolation"] },
    { id: "triceps-009", name: "Bench Dips", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["triceps"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Hands on bench", "Lower and push up"], gifUrl: "", searchTags: ["arms", "triceps", "bench dip", "bodyweight", "beginner"] },
    { id: "triceps-010", name: "JM Press", category: "strength", primaryMuscle: "arms", secondaryMuscles: ["triceps"], equipment: "barbell", difficulty: "advanced", instructions: ["Hybrid movement", "Lower to upper chest"], gifUrl: "", searchTags: ["arms", "triceps", "jm press", "barbell", "advanced"] },
  
    // CORE
    { id: "core-001", name: "Plank", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Forearms on ground", "Body in straight line", "Hold"], gifUrl: "", searchTags: ["core", "abs", "plank", "bodyweight", "isometric"] },
    { id: "core-002", name: "Side Plank", category: "core", primaryMuscle: "core", secondaryMuscles: ["obliques"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Side position", "Lift hips", "Hold"], gifUrl: "", searchTags: ["core", "obliques", "side plank", "bodyweight"] },
    { id: "core-003", name: "Crunches", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Curl shoulders off ground", "Squeeze abs"], gifUrl: "", searchTags: ["core", "abs", "crunch", "bodyweight", "beginner"] },
    { id: "core-004", name: "Bicycle Crunches", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs", "obliques"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Elbow to opposite knee", "Alternate"], gifUrl: "", searchTags: ["core", "abs", "obliques", "bicycle", "crunch"] },
    { id: "core-005", name: "Russian Twists", category: "core", primaryMuscle: "core", secondaryMuscles: ["obliques"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Lean back", "Twist side to side"], gifUrl: "", searchTags: ["core", "obliques", "russian twist", "rotation"] },
    { id: "core-006", name: "Hanging Leg Raises", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "bodyweight", difficulty: "advanced", instructions: ["Hang from bar", "Raise legs up"], gifUrl: "", searchTags: ["core", "abs", "hanging leg raise", "bodyweight", "advanced"] },
    { id: "core-007", name: "Hanging Knee Raises", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Bring knees to chest", "Lower with control"], gifUrl: "", searchTags: ["core", "abs", "hanging knee raise", "bodyweight"] },
    { id: "core-008", name: "Ab Wheel Rollout", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "other", difficulty: "advanced", instructions: ["Roll forward", "Pull back with abs"], gifUrl: "", searchTags: ["core", "abs", "ab wheel", "rollout", "advanced"] },
    { id: "core-009", name: "Mountain Climbers", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs", "cardio"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Plank position", "Drive knees to chest"], gifUrl: "", searchTags: ["core", "abs", "mountain climber", "cardio", "bodyweight"] },
    { id: "core-010", name: "Dead Bug", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Lower opposite arm and leg", "Alternate"], gifUrl: "", searchTags: ["core", "abs", "dead bug", "bodyweight", "stability"] },
    { id: "core-011", name: "Cable Crunch", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "cable", difficulty: "intermediate", instructions: ["Kneel at cable", "Crunch down"], gifUrl: "", searchTags: ["core", "abs", "crunch", "cable", "rope"] },
    { id: "core-012", name: "Pallof Press", category: "core", primaryMuscle: "core", secondaryMuscles: ["obliques"], equipment: "cable", difficulty: "intermediate", instructions: ["Press forward", "Fight rotation"], gifUrl: "", searchTags: ["core", "obliques", "pallof press", "cable", "anti-rotation"] },
    { id: "core-013", name: "Woodchoppers", category: "core", primaryMuscle: "core", secondaryMuscles: ["obliques"], equipment: "cable", difficulty: "intermediate", instructions: ["Pull cable down and across"], gifUrl: "", searchTags: ["core", "obliques", "woodchopper", "cable", "rotation"] },
    { id: "core-014", name: "Dragon Flag", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "bodyweight", difficulty: "advanced", instructions: ["Raise body vertical", "Lower with control"], gifUrl: "", searchTags: ["core", "abs", "dragon flag", "bodyweight", "advanced"] },
    { id: "core-015", name: "L-Sit", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "bodyweight", difficulty: "advanced", instructions: ["Lift legs to 90 degrees", "Hold"], gifUrl: "", searchTags: ["core", "abs", "l-sit", "bodyweight", "isometric", "gymnastics"] },
    { id: "core-016", name: "Sit-Ups", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Full sit up movement"], gifUrl: "", searchTags: ["core", "abs", "sit up", "bodyweight"] },
    { id: "core-017", name: "V-Ups", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Raise arms and legs simultaneously"], gifUrl: "", searchTags: ["core", "abs", "v-up", "bodyweight"] },
    { id: "core-018", name: "Reverse Crunches", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Bring knees to chest", "Lift hips off ground"], gifUrl: "", searchTags: ["core", "abs", "reverse crunch", "lower abs"] },
    { id: "core-019", name: "Flutter Kicks", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Alternate leg kicks", "Keep lower back on ground"], gifUrl: "", searchTags: ["core", "abs", "flutter kick", "bodyweight"] },
    { id: "core-020", name: "Hollow Body Hold", category: "core", primaryMuscle: "core", secondaryMuscles: ["abs"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Create hollow body position", "Hold"], gifUrl: "", searchTags: ["core", "abs", "hollow body", "isometric", "gymnastics"] },
  
    // OLYMPIC LIFTS
    { id: "olympic-001", name: "Power Clean", category: "strength", primaryMuscle: "full body", secondaryMuscles: ["legs", "back", "shoulders"], equipment: "barbell", difficulty: "advanced", instructions: ["Pull from floor to shoulders", "Catch in quarter squat"], gifUrl: "", searchTags: ["olympic", "clean", "power", "barbell", "explosive", "full body"] },
    { id: "olympic-002", name: "Hang Clean", category: "strength", primaryMuscle: "full body", secondaryMuscles: ["legs", "back"], equipment: "barbell", difficulty: "advanced", instructions: ["Start from hang position", "Pull to shoulders"], gifUrl: "", searchTags: ["olympic", "clean", "hang", "barbell", "explosive"] },
    { id: "olympic-003", name: "Clean and Jerk", category: "strength", primaryMuscle: "full body", secondaryMuscles: ["legs", "shoulders"], equipment: "barbell", difficulty: "advanced", instructions: ["Clean to shoulders", "Jerk overhead"], gifUrl: "", searchTags: ["olympic", "clean", "jerk", "barbell", "full body"] },
    { id: "olympic-004", name: "Power Snatch", category: "strength", primaryMuscle: "full body", secondaryMuscles: ["back", "shoulders"], equipment: "barbell", difficulty: "advanced", instructions: ["Pull from floor overhead", "Wide grip"], gifUrl: "", searchTags: ["olympic", "snatch", "power", "barbell", "explosive"] },
    { id: "olympic-005", name: "Hang Snatch", category: "strength", primaryMuscle: "full body", secondaryMuscles: ["back", "shoulders"], equipment: "barbell", difficulty: "advanced", instructions: ["Hang position to overhead", "One motion"], gifUrl: "", searchTags: ["olympic", "snatch", "hang", "barbell"] },
    { id: "olympic-006", name: "Push Press", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["legs", "triceps"], equipment: "barbell", difficulty: "intermediate", instructions: ["Slight dip", "Drive bar overhead"], gifUrl: "", searchTags: ["olympic", "push press", "shoulders", "barbell", "explosive"] },
    { id: "olympic-007", name: "Push Jerk", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["legs"], equipment: "barbell", difficulty: "advanced", instructions: ["Dip and drive", "Catch in quarter squat"], gifUrl: "", searchTags: ["olympic", "jerk", "push", "barbell", "explosive"] },
    { id: "olympic-008", name: "Split Jerk", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["legs"], equipment: "barbell", difficulty: "advanced", instructions: ["Catch in split stance", "Drive overhead"], gifUrl: "", searchTags: ["olympic", "jerk", "split", "barbell"] },
    { id: "olympic-009", name: "Muscle Snatch", category: "strength", primaryMuscle: "back", secondaryMuscles: ["shoulders"], equipment: "barbell", difficulty: "advanced", instructions: ["Pull bar overhead", "No catch"], gifUrl: "", searchTags: ["olympic", "snatch", "muscle", "barbell", "accessory"] },
    { id: "olympic-010", name: "Muscle Clean", category: "strength", primaryMuscle: "back", secondaryMuscles: ["shoulders"], equipment: "barbell", difficulty: "advanced", instructions: ["Pull to shoulders", "No catch"], gifUrl: "", searchTags: ["olympic", "clean", "muscle", "barbell", "accessory"] },
  
    // STRONGMAN
    { id: "strongman-001", name: "Farmer's Walk", category: "strength", primaryMuscle: "full body", secondaryMuscles: ["forearms", "traps", "core"], equipment: "other", difficulty: "intermediate", instructions: ["Carry heavy weights", "Walk distance"], gifUrl: "", searchTags: ["strongman", "farmers walk", "carry", "grip", "full body"] },
    { id: "strongman-002", name: "Yoke Walk", category: "strength", primaryMuscle: "full body", secondaryMuscles: ["legs", "back"], equipment: "other", difficulty: "advanced", instructions: ["Carry yoke on shoulders", "Walk"], gifUrl: "", searchTags: ["strongman", "yoke", "carry", "walk", "full body"] },
    { id: "strongman-003", name: "Atlas Stone Lift", category: "strength", primaryMuscle: "full body", secondaryMuscles: ["back", "legs"], equipment: "other", difficulty: "advanced", instructions: ["Lift stone to platform"], gifUrl: "", searchTags: ["strongman", "atlas stone", "lift", "full body"] },
    { id: "strongman-004", name: "Tire Flip", category: "strength", primaryMuscle: "full body", secondaryMuscles: ["legs", "back"], equipment: "other", difficulty: "advanced", instructions: ["Flip large tire"], gifUrl: "", searchTags: ["strongman", "tire flip", "explosive", "full body"] },
    { id: "strongman-005", name: "Sled Push", category: "conditioning", primaryMuscle: "legs", secondaryMuscles: ["cardio"], equipment: "other", difficulty: "intermediate", instructions: ["Push weighted sled"], gifUrl: "", searchTags: ["strongman", "sled push", "legs", "conditioning"] },
    { id: "strongman-006", name: "Sled Drag", category: "conditioning", primaryMuscle: "legs", secondaryMuscles: ["back"], equipment: "other", difficulty: "intermediate", instructions: ["Drag sled backward"], gifUrl: "", searchTags: ["strongman", "sled drag", "legs", "conditioning"] },
    { id: "strongman-007", name: "Sandbag Carry", category: "strength", primaryMuscle: "full body", secondaryMuscles: ["core", "shoulders"], equipment: "other", difficulty: "intermediate", instructions: ["Carry sandbag", "Distance"], gifUrl: "", searchTags: ["strongman", "sandbag", "carry", "unstable"] },
    { id: "strongman-008", name: "Log Press", category: "strength", primaryMuscle: "shoulders", secondaryMuscles: ["legs"], equipment: "other", difficulty: "advanced", instructions: ["Clean log to shoulders", "Press overhead"], gifUrl: "", searchTags: ["strongman", "log press", "overhead", "shoulders"] },
    { id: "strongman-009", name: "Axle Bar Deadlift", category: "strength", primaryMuscle: "back", secondaryMuscles: ["legs", "grip"], equipment: "barbell", difficulty: "advanced", instructions: ["Thick bar deadlift", "Challenges grip"], gifUrl: "", searchTags: ["strongman", "axle", "deadlift", "thick bar", "grip"] },
    { id: "strongman-010", name: "Keg Toss", category: "strength", primaryMuscle: "full body", secondaryMuscles: ["shoulders"], equipment: "other", difficulty: "advanced", instructions: ["Toss keg over bar"], gifUrl: "", searchTags: ["strongman", "keg", "toss", "explosive"] },
  
    // CARDIO & CONDITIONING
    { id: "cardio-001", name: "Burpees", category: "cardio", primaryMuscle: "full body", secondaryMuscles: ["cardio"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Drop to ground", "Push up", "Jump up"], gifUrl: "", searchTags: ["cardio", "burpee", "full body", "conditioning", "bodyweight"] },
    { id: "cardio-002", name: "Box Jumps", category: "cardio", primaryMuscle: "legs", secondaryMuscles: ["cardio"], equipment: "other", difficulty: "intermediate", instructions: ["Jump onto box", "Step down"], gifUrl: "", searchTags: ["cardio", "box jump", "plyometric", "explosive", "legs"] },
    { id: "cardio-003", name: "Battle Ropes", category: "cardio", primaryMuscle: "arms", secondaryMuscles: ["cardio", "shoulders"], equipment: "other", difficulty: "intermediate", instructions: ["Wave ropes alternating", "High intensity"], gifUrl: "", searchTags: ["cardio", "battle rope", "conditioning", "arms", "shoulders"] },
    { id: "cardio-004", name: "Jump Rope", category: "cardio", primaryMuscle: "cardio", secondaryMuscles: ["calves"], equipment: "other", difficulty: "beginner", instructions: ["Jump rope continuously"], gifUrl: "", searchTags: ["cardio", "jump rope", "conditioning", "calves"] },
    { id: "cardio-005", name: "Sprints", category: "cardio", primaryMuscle: "legs", secondaryMuscles: ["cardio"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Max effort running"], gifUrl: "", searchTags: ["cardio", "sprint", "running", "legs", "explosive"] },
    { id: "cardio-006", name: "Rowing Machine", category: "cardio", primaryMuscle: "back", secondaryMuscles: ["cardio", "legs"], equipment: "machine", difficulty: "beginner", instructions: ["Row for distance/time"], gifUrl: "", searchTags: ["cardio", "rowing", "machine", "full body"] },
    { id: "cardio-007", name: "Assault Bike", category: "cardio", primaryMuscle: "cardio", secondaryMuscles: ["legs", "arms"], equipment: "machine", difficulty: "intermediate", instructions: ["Bike at high intensity"], gifUrl: "", searchTags: ["cardio", "assault bike", "air bike", "conditioning"] },
    { id: "cardio-008", name: "Stair Climber", category: "cardio", primaryMuscle: "legs", secondaryMuscles: ["cardio"], equipment: "machine", difficulty: "beginner", instructions: ["Climb stairs continuously"], gifUrl: "", searchTags: ["cardio", "stairs", "stairmaster", "legs"] },
    { id: "cardio-009", name: "Treadmill Running", category: "cardio", primaryMuscle: "cardio", secondaryMuscles: ["legs"], equipment: "machine", difficulty: "beginner", instructions: ["Run on treadmill"], gifUrl: "", searchTags: ["cardio", "treadmill", "running", "legs"] },
    { id: "cardio-010", name: "Elliptical", category: "cardio", primaryMuscle: "cardio", secondaryMuscles: ["legs"], equipment: "machine", difficulty: "beginner", instructions: ["Low impact cardio"], gifUrl: "", searchTags: ["cardio", "elliptical", "low impact", "legs"] },
    { id: "cardio-011", name: "High Knees", category: "cardio", primaryMuscle: "cardio", secondaryMuscles: ["legs"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Run in place", "Knees high"], gifUrl: "", searchTags: ["cardio", "high knees", "running", "bodyweight"] },
    { id: "cardio-012", name: "Jumping Jacks", category: "cardio", primaryMuscle: "cardio", secondaryMuscles: ["full body"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Jump with arms and legs out"], gifUrl: "", searchTags: ["cardio", "jumping jack", "warm up", "bodyweight"] },
    { id: "cardio-013", name: "Mountain Climbers", category: "cardio", primaryMuscle: "core", secondaryMuscles: ["cardio"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Plank position", "Drive knees"], gifUrl: "", searchTags: ["cardio", "mountain climber", "core", "conditioning"] },
    { id: "cardio-014", name: "Skipping", category: "cardio", primaryMuscle: "cardio", secondaryMuscles: ["legs"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Skip forward"], gifUrl: "", searchTags: ["cardio", "skip", "warm up", "legs"] },
    { id: "cardio-015", name: "Shadow Boxing", category: "cardio", primaryMuscle: "cardio", secondaryMuscles: ["arms"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Throw punches", "Move around"], gifUrl: "", searchTags: ["cardio", "boxing", "shadowbox", "conditioning"] },
  
    // STRETCHING & MOBILITY
    { id: "stretch-001", name: "Standing Hamstring Stretch", category: "mobility", primaryMuscle: "hamstrings", secondaryMuscles: [], equipment: "bodyweight", difficulty: "beginner", instructions: ["Reach for toes", "Hold stretch"], gifUrl: "", searchTags: ["stretch", "hamstrings", "flexibility", "mobility"] },
    { id: "stretch-002", name: "Quad Stretch", category: "mobility", primaryMuscle: "quads", secondaryMuscles: [], equipment: "bodyweight", difficulty: "beginner", instructions: ["Pull foot to glute", "Hold"], gifUrl: "", searchTags: ["stretch", "quads", "quadriceps", "flexibility"] },
    { id: "stretch-003", name: "Hip Flexor Stretch", category: "mobility", primaryMuscle: "hips", secondaryMuscles: [], equipment: "bodyweight", difficulty: "beginner", instructions: ["Lunge position", "Push hips forward"], gifUrl: "", searchTags: ["stretch", "hip flexor", "hips", "mobility"] },
    { id: "stretch-004", name: "Shoulder Dislocations", category: "mobility", primaryMuscle: "shoulders", secondaryMuscles: [], equipment: "other", difficulty: "beginner", instructions: ["Pass band overhead", "Behind and back"], gifUrl: "", searchTags: ["mobility", "shoulder", "dislocations", "warm up"] },
    { id: "stretch-005", name: "Cat-Cow Stretch", category: "mobility", primaryMuscle: "back", secondaryMuscles: ["core"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Arch and round back", "Alternate"], gifUrl: "", searchTags: ["stretch", "mobility", "cat cow", "spine", "back"] },
    { id: "stretch-006", name: "Child's Pose", category: "mobility", primaryMuscle: "back", secondaryMuscles: [], equipment: "bodyweight", difficulty: "beginner", instructions: ["Sit back on heels", "Reach forward"], gifUrl: "", searchTags: ["stretch", "childs pose", "back", "rest"] },
    { id: "stretch-007", name: "Pigeon Pose", category: "mobility", primaryMuscle: "hips", secondaryMuscles: ["glutes"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Front leg bent", "Back leg extended", "Lean forward"], gifUrl: "", searchTags: ["stretch", "pigeon", "hips", "glutes", "flexibility"] },
    { id: "stretch-008", name: "Downward Dog", category: "mobility", primaryMuscle: "full body", secondaryMuscles: ["hamstrings", "shoulders"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Inverted V position", "Press heels down"], gifUrl: "", searchTags: ["stretch", "downward dog", "yoga", "full body"] },
    { id: "stretch-009", name: "Couch Stretch", category: "mobility", primaryMuscle: "hips", secondaryMuscles: ["quads"], equipment: "bodyweight", difficulty: "intermediate", instructions: ["Back knee on ground", "Against wall", "Upright torso"], gifUrl: "", searchTags: ["stretch", "couch", "hip flexor", "quads", "mobility"] },
    { id: "stretch-010", name: "Seated Forward Fold", category: "mobility", primaryMuscle: "hamstrings", secondaryMuscles: ["back"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Sit with legs extended", "Reach for toes"], gifUrl: "", searchTags: ["stretch", "seated", "hamstrings", "forward fold"] },
  
    // ACCESSORY & SPECIALTY
    { id: "accessory-001", name: "Wrist Curls", category: "strength", primaryMuscle: "forearms", secondaryMuscles: [], equipment: "dumbbell", difficulty: "beginner", instructions: ["Curl wrists up", "Forearm on bench"], gifUrl: "", searchTags: ["forearms", "wrist curl", "grip", "dumbbell"] },
    { id: "accessory-002", name: "Reverse Wrist Curls", category: "strength", primaryMuscle: "forearms", secondaryMuscles: [], equipment: "dumbbell", difficulty: "beginner", instructions: ["Curl wrists up", "Palms down"], gifUrl: "", searchTags: ["forearms", "wrist curl", "reverse", "grip"] },
    { id: "accessory-003", name: "Finger Curls", category: "strength", primaryMuscle: "forearms", secondaryMuscles: [], equipment: "barbell", difficulty: "beginner", instructions: ["Roll bar in fingers"], gifUrl: "", searchTags: ["forearms", "finger curl", "grip", "hands"] },
    { id: "accessory-004", name: "Dead Hang", category: "strength", primaryMuscle: "forearms", secondaryMuscles: ["back"], equipment: "bodyweight", difficulty: "beginner", instructions: ["Hang from bar", "Hold for time"], gifUrl: "", searchTags: ["forearms", "grip", "dead hang", "hang", "bodyweight"] },
    { id: "accessory-005", name: "Band Pull-Aparts", category: "strength", primaryMuscle: "back", secondaryMuscles: ["rear delts"], equipment: "other", difficulty: "beginner", instructions: ["Pull band apart", "Squeeze shoulder blades"], gifUrl: "", searchTags: ["back", "rear delts", "band", "pull apart", "posture"] },
    { id: "accessory-006", name: "Plate Pinch", category: "strength", primaryMuscle: "forearms", secondaryMuscles: [], equipment: "other", difficulty: "beginner", instructions: ["Pinch plates", "Hold for time"], gifUrl: "", searchTags: ["forearms", "grip", "plate pinch", "hands"] },
    { id: "accessory-007", name: "Neck Curls", category: "strength", primaryMuscle: "neck", secondaryMuscles: [], equipment: "bodyweight", difficulty: "beginner", instructions: ["Lie on back", "Curl neck up"], gifUrl: "", searchTags: ["neck", "curl", "strength", "bodyweight"] },
    { id: "accessory-008", name: "Neck Extensions", category: "strength", primaryMuscle: "neck", secondaryMuscles: [], equipment: "bodyweight", difficulty: "beginner", instructions: ["Face down", "Extend neck up"], gifUrl: "", searchTags: ["neck", "extension", "strength"] },
    { id: "accessory-009", name: "Lateral Neck Flexion", category: "strength", primaryMuscle: "neck", secondaryMuscles: [], equipment: "bodyweight", difficulty: "beginner", instructions: ["Tilt head to side", "Against resistance"], gifUrl: "", searchTags: ["neck", "lateral", "side", "strength"] },
    { id: "accessory-010", name: "Towel Pull-Ups", category: "strength", primaryMuscle: "back", secondaryMuscles: ["forearms"], equipment: "bodyweight", difficulty: "advanced", instructions: ["Grip towel over bar", "Pull up"], gifUrl: "", searchTags: ["back", "grip", "pull up", "towel", "forearms", "advanced"] },
    
  ];
  
  export default exerciseDatabase;
  
  // SEARCH FUNCTIONS
  
  export const searchExercises = (query) => {
    if (!query || query.length < 2) return [];
    
    const searchTerm = query.toLowerCase().trim();
    
    return exerciseDatabase.filter(exercise => {
      if (exercise.name.toLowerCase().includes(searchTerm)) return true;
      if (exercise.primaryMuscle.toLowerCase().includes(searchTerm)) return true;
      if (exercise.secondaryMuscles.some(muscle => muscle.toLowerCase().includes(searchTerm))) return true;
      if (exercise.equipment.toLowerCase().includes(searchTerm)) return true;
      if (exercise.category.toLowerCase().includes(searchTerm)) return true;
      if (exercise.searchTags.some(tag => tag.toLowerCase().includes(searchTerm))) return true;
      return false;
    });
  };
  
  export const getExercisesByMuscle = (muscle) => {
    const muscleLower = muscle.toLowerCase();
    return exerciseDatabase.filter(exercise => 
      exercise.primaryMuscle.toLowerCase() === muscleLower ||
      exercise.secondaryMuscles.some(m => m.toLowerCase() === muscleLower)
    );
  };
  
  export const getExercisesByEquipment = (equipment) => {
    return exerciseDatabase.filter(exercise => 
      exercise.equipment.toLowerCase() === equipment.toLowerCase()
    );
  };
  
  export const getExercisesByDifficulty = (difficulty) => {
    return exerciseDatabase.filter(exercise => 
      exercise.difficulty.toLowerCase() === difficulty.toLowerCase()
    );
  };
  
  export const getExercisesByCategory = (category) => {
    return exerciseDatabase.filter(exercise => 
      exercise.category.toLowerCase() === category.toLowerCase()
    );
  };